version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - yum groupinstall -y "Development Tools"
      - yum install -y cmake3.x86_64
  build:
    commands:
       - echo Entered the build phase...
       - echo Entered the build phase...
       - mkdir build
       - cd build
       - cmake3 ../ -DENABLE_GIST=NO
       - make -j 2
       - cd ../

artifacts:
  files:
    - build/*.a
    - build/bin/fzn-gecode
